server:
  port: 8882

spring:
  mail:
    # 邮件服务器地址
    host: smtp.qq.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: utf-8
    # 授权码
    password: xftczyjifersdhgd
    # 发送者邮箱地址
    username: 2570650250@qq.com
    # 端口
    port: 25

  rabbitmq:
    username: admin
    password: 123456
    host: 192.168.64.137
    port: 5672
    listener:
      simple:
        # 开启手动确认
        acknowledge-mode: manual

  redis:
    # 超时时间
    timeout: 10000ms
    # 服务地址
    host: 192.168.64.137
    # 服务端口
    port: 5002
    # 数据库
    database: 2
    lettuce:
      pool:
        # 最小空闲连接
        min-idle: 5
        # 最大连接数
        max-active: 1024
        # 最大连接阻塞时间
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200