server:
  port: 8087

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间
      idle-timeout: 100000
      # 最大连接数
      maximum-pool-size: 10
      # 自动提交
      auto-commit: true
      # 连接最大存活时间(30m)
      max-lifetime: 1800000
      # 连接超时时间(30s)
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  # redis 配置
  redis:
    # 超时时间
    timeout: 10000ms
    # 服务地址
    host: 192.168.64.137
    # 服务端口
    port: 5002
    # 数据库
    database: 1
    lettuce:
      pool:
        # 最小空闲连接
        min-idle: 5
        # 最大连接数
        max-active: 1024
        # 最大连接阻塞时间
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200

  rabbitmq:
    username: admin
    password: 123456
    host: 192.168.64.137
    port: 5672
    # 消息确认回调
    publisher-confirm-type: correlated
    # 消息失败回调
    publisher-returns: true


# mybatis-plus配置
mybatis-plus:
  # 配置mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置mybatis数据返回类型别名
  type-aliases-package: com.kai.server.pojo
  # 自动驼峰命名
  configuration:
    map-underscore-to-camel-case: false

# Mybatis SQL 打印(方法接口所在的包,不是Mapper.xml所在的包)
logging:
  level:
    com.kai.server.mapper: debug


jwt:
  # jwt 存储的请求头
  tokenHeader: Authorization
  # jwt 加密解密使用的密钥
  secret: yeb-secret
  # jwt 的超期限时间(60*60*24)
  expiration: 604800
  # jwt 负载中拿到开头
  tokenHead: Bearer