
spring:
  # thymeleaf 配置
  thymeleaf:
    # 关闭缓存
    cache: false
    # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    # 阿里云服务器 MySQL8.0 Docker
    url: jdbc:mysql://39.101.135.86:3311/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      pool-name: DateHikaryiCP
      minimum-idle: 5
      # 空闲连接存活最大时间,默认600000(10分钟)
      idle-timeout: 1800000
      # 最大连接数,默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间,默认30分钟
      max-lifetime: 1800000
      # 连接超时时间,默认30s
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  # redis 配置
  redis:
    # 虚拟机地址
    host: 192.168.64.137
    # 端口号,默认6379
    port: 5002
    # 操作数据库,默认0库
    database: 0
    # 连接超时时间
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数,默认8
        max-active: 8
        # 最大连接阻塞等待时间,默认-1
        max-wait: 10000ms
        # 最大空闲连接,默认8
        max-idle: 200
        # 最小空闲连接,默认0
        min-idle: 0


# Mybatis-plus配置
mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名(默认为类名)
  type-aliases-package: com.kai.seckill.pojo

# Mybatis SQL 打印
logging:
  level:
    com.kai.seckill.mapper: debug
server:
  port: 8088
